spring:
  ai:
    dashscope:
      api-key: sk-9da43415eac4485981ee70295f187c16
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          temperature: 0.7
          top-p: 0.8
  datasource:
    url: jdbc:mysql://192.168.1.200:3306/chat_ai?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 可选：JPA 或 MyBatis-Plus 设置
  data:
    redis:
      host: 192.168.1.200
      port: 6379
      timeout: 3000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL
  global-config:
    db-config:
      id-type: auto
chat:
  memory:
    key-prefix: "chat:mem:"
    retrieve-size: 5 #取的历史个数<=max-messages
    max-messages: 10 #最大10条消息可调(redis)
    ttl-seconds: 604800  # 7天

